apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: email-sanitize-microservice
  description: API to sanitize email addresses from string input
  annotations:
    github.com/project-slug: thomasve-DANS/email-sanitize-microservice
spec:
  type: openapi
  lifecycle: production
  owner: thomasve
  definition: |
    openapi: 3.0.2
    info:
      title: FastAPI
      version: 0.1.0
    paths:
      "/version":
        get:
          summary: Info
            operationId: info_version_get
              responses:
                '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
    "/sanitize":
      post:
        summary: Sanitize
        description: Simple function to strip email addresses from file.
        operationId: sanitize_sanitize_post
        requestBody:
          content:
            application/json:
            schema:
              "$ref": "#/components/schemas/Data"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
    components:
      schemas:
      Data:
        title: Data
        required:
      - data
      type: object
      properties:
        data:
          title: Data
          type: string
        replacement_email:
          title: Replacement Email
          type: string
          default: ''
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            "$ref": "#/components/schemas/ValidationError"
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
