name: Docker Image CI

on:
  push:
    tags:
      - '*'

env:
  TAG: $GITHUB_REF_NAME
  ORG: odissei

jobs:
  push:
    name: Push to registry.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_PASSWORD }}

      - name: Build and push Prefect Worker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.ORG }}/emailsanitizer:${{ github.ref_name }}